name: CI

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
jobs:
    analysis:
        name: format
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Install Flutter
            uses: subosito/flutter-action@v2
            with:
              channel: 'stable'
              architecture: x64
          - name: Analyze code
            run: flutter analyze .
    flutter_tests:
        name: flutter tests
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Install Flutter
            uses: subosito/flutter-action@v2
            with:
              flutter-version: '3.19.3'
              channel: stable
              architecture: x64
          - name: Install Flutter dependencies
            run: flutter pub get
          - name: Flutter tests
            run: flutter test
    ios:
        name: ios tests
        runs-on: macos-14
        steps:
            - uses: actions/checkout@v4
            - name: Setup Flutter SDK
              uses: subosito/flutter-action@v2
              with:
                channel: stable
            - name: Install Flutter dependencies
              run: flutter pub get
            - uses: futureware-tech/simulator-action@v3
              with:
                model: 'iPhone 15'
            - name: Write sitekeys to file
              env:
                EXAMPLE_DEV_JSON: ${{ secrets.EXAMPLE_DEV_JSON }}
              run: echo "$EXAMPLE_DEV_JSON" >> example/assets/config/dev.json
            - name: Run integration tests
              run: cd example && flutter test integration_test/app_test.dart
    android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Flutter SDK
              uses: subosito/flutter-action@v2
              with:
                channel: stable
            - name: Install Flutter dependencies
              run: flutter pub get
            - name: Write sitekeys to file
              env:
                EXAMPLE_DEV_JSON: ${{ secrets.EXAMPLE_DEV_JSON }}
              run: echo "$EXAMPLE_DEV_JSON" >> example/assets/config/dev.json
            - name: Run integration tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 31
                arch: x86_64
                profile: Nexus 6      
                script: cd example && flutter test integration_test/app_test.dart --timeout none